name: Detox

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      - name: Cache node modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Rebuild detox
        if: steps.cache.outputs.cache-hit == 'true'
        run: yarn detox-setup

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Cache Pods
        uses: actions/cache@v1
        id: podcache
        with:
          path: ios/Pods
          key: pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Update Pods
        run: |
          gem update cocoapods xcodeproj
          cd ios && pod install && cd ..
      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: yarn detox-build-ios-release
      - run: yarn detox test -c ios.release --cleanup --debug-synchronization 200
